# Generated by Django 2.0.7 on 2019-01-05 00:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('hash', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True, verbose_name='Unique')),
                ('format', models.CharField(choices=[('MP3', 'Mpeg 3'), ('WMA', 'Windows Media Audio'), ('WAV', 'Wave')], max_length=3, verbose_name='Format')),
                ('size', models.IntegerField(verbose_name='Audio Size')),
                ('length', models.IntegerField(verbose_name='Audio Length')),
                ('summary', models.CharField(max_length=200, verbose_name='Audio Summary')),
                ('hidden', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Audios',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('hash', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True, verbose_name='Unique')),
                ('format', models.CharField(choices=[('DOC', 'Document'), ('PDF', 'Portable Document Format')], max_length=3, verbose_name='Format')),
                ('size', models.IntegerField(verbose_name='Document Size')),
                ('summary', models.CharField(max_length=200, verbose_name='Video Summary')),
                ('hidden', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Folder Name')),
                ('unique', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='hash')),
                ('hidden', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
            options={
                'verbose_name_plural': 'Folders',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('hash', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True, verbose_name='Unique')),
                ('format', models.CharField(choices=[('JPG', 'joint Photographics Group'), ('GIF', 'graphic interchange format'), ('PNG', 'portable network graphic')], max_length=3, verbose_name='Format')),
                ('size', models.IntegerField(verbose_name='Picture Size')),
                ('width', models.IntegerField(verbose_name='picture Frame Width')),
                ('height', models.IntegerField(verbose_name='picture Frame Height')),
                ('summary', models.CharField(max_length=200, verbose_name='picture Summary')),
                ('hidden', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='Manager.Folder')),
            ],
            options={
                'verbose_name_plural': 'Pictures',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('hash', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True, verbose_name='Unique')),
                ('format', models.CharField(choices=[('MP4', 'Mpeg 4'), ('Avi', 'Audio Video Interface'), ('MOV', 'Apple QuickTime Video')], max_length=3, verbose_name='Format')),
                ('size', models.IntegerField(verbose_name='Video Size')),
                ('length', models.IntegerField(verbose_name='Video Length')),
                ('width', models.IntegerField(verbose_name='Video Frame Width')),
                ('height', models.IntegerField(verbose_name='Video Frame Height')),
                ('summary', models.CharField(max_length=200, verbose_name='Video Summary')),
                ('hidden', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='Manager.Folder')),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='Manager.Folder'),
        ),
        migrations.AddField(
            model_name='audio',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='Manager.Folder'),
        ),
    ]
