# Generated by Django 2.1.5 on 2019-01-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='length',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='length',
        ),
        migrations.AlterField(
            model_name='audio',
            name='format',
            field=models.CharField(choices=[('MP3', 'MP3'), ('WMA', 'WMA'), ('WAV', 'WAV')], max_length=3, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='document',
            name='format',
            field=models.CharField(choices=[('DOC', 'DOC'), ('PDF', 'PDF')], max_length=3, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='format',
            field=models.CharField(choices=[('MP4', 'MP4'), ('AVI', 'AVI'), ('MOV', 'MOV')], max_length=3, verbose_name='Format'),
        ),
    ]
