# Generated by Django 2.0.7 on 2018-12-20 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_auto_20181220_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='unique',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='hash'),
        ),
    ]
