# Generated by Django 2.1.5 on 2019-01-07 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_auto_20190106_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='height',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='width',
        ),
    ]
