# Generated by Django 2.0.7 on 2018-12-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0005_auto_20181222_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='quantity',
        ),
    ]
