# Generated by Django 2.1.5 on 2019-01-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0005_auto_20190108_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='height',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='width',
        ),
    ]
