# Generated by Django 2.0.7 on 2018-12-27 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0006_remove_folder_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='music', to='Manager.Folder'),
        ),
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='document', to='Manager.Folder'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gallery', to='Manager.Folder'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movies', to='Manager.Folder'),
        ),
    ]
