# Generated by Django 2.0.7 on 2019-01-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0008_auto_20190101_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='file_name',
            new_name='hash',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='file_name',
            new_name='hash',
        ),
        migrations.RenameField(
            model_name='pictures',
            old_name='file_name',
            new_name='hash',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='file_name',
            new_name='hash',
        ),
        migrations.AlterField(
            model_name='document',
            name='format',
            field=models.CharField(choices=[('DOC', 'Document'), ('PDF', 'Portable Document Format')], max_length=3, verbose_name='Format'),
        ),
    ]
